modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/CoffeeCatRailway/ColorMod/issues"

[[mods]]
modId="${modId}"
version="${version}"
displayName="${name}"
credits="To Forge for always being better then fabric."
authors="${author}"
description='''
Tis a color mod.
'''

[[dependencies.coffeecolor]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.coffeecolor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.coffeecolor]]
    modId="curios"
    mandatory=true
    versionRange="[FORGE-1.15.2-2,]"
    ordering="NONE"
    side="BOTH"
